:_module-type: PROCEDURE

[id='storing-data-with-connections']
= Data Connections

[role="_abstract"]
A Data Connection is a resource that has the configuration parameters needed to connect to a data source or data sink, such as an AWS S3 object storage bucket. You can connect them to workbenches or pipelines for easier access to the data source.

For this {deliverable}, you will have two data connections that point to two different S3 buckets:

* *Pipelines Artifacts* - Use this bucket as storage for your pipeline artifacts. When you create a pipeline server, you need a pipeline artifacts bucket.
* *Data* - This bucket contains the PDF documents which will be consumed by the pipeline in the RAG section.

NOTE: You can also use storage buckets for storing artifacts such as models, take a look at the link:https://rh-aiservices-bu.github.io/fraud-detection/fraud-detection-workshop/index.html[Fraud Detection^] {deliverable} for such an example.

Choose one of the following options:

* *Use the provided script (recommended):* Runs a script that installs a local S3-compatible storage service and creates the data connections automatically. xref:1-setup/3-scripted-storage.adoc[Follow these steps].
* *Use your own S3-compatible object storage:* If you already have S3 buckets you want to use, you can create the connections manually. xref:1-setup/4-manual-storage.adoc[Follow these steps].
