apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  name: mcp-ticketing
  annotations:
    mcp.opendatahub.io/catalog-server: mcp-ticketing
    mcp.opendatahub.io/display-name: Hospital IT Ticketing
spec:
  config:
    path: /mcp
    port: 8080
  source:
    containerImage:
      ref: quay.io/rlundber/hospital-helpdesk-mcp-ticketing:0.3
    type: ContainerImage
